import logging
import random

from lib.discrete_event_sim_components import Counter
from lib.phy import airtime, estimate_path_loss

NODENUM_BROADCAST = 0xFFFFFFFF

logger = logging.getLogger(__name__)

class MeshPacket:
    unique_packet_counter = Counter()
    asym_rng = random.Random(44) # same default seed as in lib/config.py

    @staticmethod
    def seed_asym_rng(seed):
        MeshPacket.asym_rng.seed(seed)

    @staticmethod
    def reset_packet_counter():
        MeshPacket.unique_packet_counter = Counter()

    def __init__(self, conf, nodes, origTxNodeId, destId, txNodeId, plen, seq, genTime, wantAck, isAck, requestId, now, connectivity_map, baseline_pathloss_matrix):
        """Create a new packet and calculate which nodes sense and receive it

        Arguments:
        conf -- simulation Config
        nodes -- set of all nodes in the simulation. For calculating which nodes receive the packet
        origTxNodeId -- ID of originating node
        destId -- ID of destination node (specific node or broadcast)
        txNodeId -- ID of currently transmitting node
        plen -- packet length
        seq -- message sequence number
        genTime -- sim time of original packet generation (different from acks/rebroadcasts)
        wantAck -- this packet wants an ACK
        isAck -- this packet is an ACK packet
        requestId -- ID of packet requesting ACK (only valid for ACK packets)
        now -- current sim time when called, always `env.now`
        connectivity_map -- map of nodeid -> set of reachable nodeids
        baseline_pathloss_matrix -- pre-computed matrix of pathloss between nodes
        """
        self.unique_packet_seq = MeshPacket.unique_packet_counter.get()
        self.conf = conf
        self.origTxNodeId = origTxNodeId
        self.destId = destId
        self.txNodeId = txNodeId
        self.wantAck = wantAck
        self.isAck = isAck
        self.seq = seq
        self.requestId = requestId
        self.genTime = genTime
        self.now = now
        self.txpow = self.conf.PTX
        self.LplAtN = [0 for _ in range(self.conf.NR_NODES)]
        self.rssiAtN = [0 for _ in range(self.conf.NR_NODES)]
        self.sensedByN = [False for _ in range(self.conf.NR_NODES)] # nodes which may possibly sense this packet
        self.detectedByN = [False for _ in range(self.conf.NR_NODES)]
        self.collidedAtN = [False for _ in range(self.conf.NR_NODES)]
        self.receivedAtN = [False for _ in range(self.conf.NR_NODES)]
        self.onAirToN = [True for _ in range(self.conf.NR_NODES)]

        # configuration values
        self.sf = self.conf.current_preset["sf"]
        self.cr = self.conf.current_preset["cr"]
        self.bw = self.conf.current_preset["bw"]
        self.freq = self.conf.FREQ
        self.tx_node = next(n for n in nodes if n.nodeid == self.txNodeId)

        logger.debug(f"{self.now:.3f} Packet {self.unique_packet_seq} for msg {self.seq} generated by node {self.txNodeId}")

        # calculate reception at all other nodes
        for rx_node in nodes:
            if rx_node.nodeid == self.txNodeId:
                continue

            # reduce calculations just to plausibly reachable nodes. This is initialized
            # before sim start, and updated whenever a moving node's position is updated,
            # so is always an accurate map of what nodes could (with extra margin) even
            # sense each other.
            if self.conf.ENABLE_CONNECTIVITY_MAP and not connectivity_map[self.txNodeId].__contains__(rx_node.nodeid):
                logger.debug(f"{self.now:.3f} skipping {self.txNodeId} -> {rx_node.nodeid} computation. connectivity map: {connectivity_map[self.txNodeId]}")
                if conf.MODEL_ASYMMETRIC_LINKS:
                    # Each tx -> rx computation we skip gets the asrm_rng one call out
                    # of sync between simulations with and without the connectivity
                    # map optimization. Thus particular tx -> rx calculations
                    # change between the optimization, which can lead to changes
                    # in sim behavior between the optimization being on/off, leading
                    # to inconsistencies beteen the optimization being on/off.
                    #
                    # Keep things balanced by 'unnecessarily' calling the rng here.
                    MeshPacket.asym_rng.gauss(0, conf.MODEL_ASYMMETRIC_LINKS_STDDEV)
                continue

            if self.conf.ENABLE_CONNECTIVITY_MAP:
                # look up baseline path loss from matrix, since we've already computed it.
                baseline_pathloss = baseline_pathloss_matrix[self.txNodeId][rx_node.nodeid]
            else:
                dist_3d = self.tx_node.position.euclidean_distance(rx_node.position)
                baseline_pathloss = estimate_path_loss(self.conf, dist_3d, self.freq, self.tx_node.position.z, rx_node.position.z)

            if conf.MODEL_ASYMMETRIC_LINKS:
                offset = MeshPacket.asym_rng.gauss(0, conf.MODEL_ASYMMETRIC_LINKS_STDDEV)
                logger.debug(f"{self.now:.3f} packet {self.unique_packet_seq} for msg {self.seq} has asym offset {offset} dB")
                if abs(offset) > conf.CONNECTIVITY_MAP_RSSI_MARGIN:
                    logger.warning(f"{self.now:.3f} packet {self.unique_packet_counter} has asymmetric RSSI offset {offset} which is outside margin. This will lead to inconsistent results with the connectivity map optimization.")
            else:
                offset = 0
            self.LplAtN[rx_node.nodeid] = baseline_pathloss + offset
            self.rssiAtN[rx_node.nodeid] = self.txpow + self.tx_node.antennaGain + rx_node.antennaGain - self.LplAtN[rx_node.nodeid]
            if self.rssiAtN[rx_node.nodeid] >= self.conf.current_preset["sensitivity"]:
                self.sensedByN[rx_node.nodeid] = True
            if self.rssiAtN[rx_node.nodeid] >= self.conf.current_preset["cad_threshold"]:
                self.detectedByN[rx_node.nodeid] = True

        self.packetLen = plen
        self.timeOnAir = airtime(self.conf, self.sf, self.cr, self.packetLen, self.bw)
        self.startTime = 0
        self.endTime = 0

        # Routing
        self.retransmissions = self.conf.maxRetransmission
        self.ackReceived = False

        # ADAPTIVE_RELAY protocol extensions (inert for other routers; all
        # defaults are no-ops and MANAGED_FLOOD never reads or sets them):
        # ordered relay designation (analogue of firmware `relay_node` header,
        # extended to a short ordered list). None/[] = no designation.
        self.relay_designation = None
        # bounded mini-flood radius; 0 = no flooding contract on this copy
        self.flood_ttl = 0
        # payload-carried sender position (only set for POSITION messages,
        # mirroring Meshtastic position broadcasts)
        self.pos_x = None
        self.pos_y = None
        # designated-primary relays use the short (router-style) contention
        # window — only one designated transmitter per hop. Inert for other
        # routers (never set).
        self.fast_cw = False
        # EXPERIMENTAL (ablated): skip dupe-cancel for designated primaries.
        # Inert unless AR_PARAMS['primary_bypass_dupe_cancel'] is set.
        self.no_dupe_cancel = False
        # v0.5 reach-first guard marker (set only by ADAPTIVE_RELAY)
        self.ar_guard = False
        # NEIGHBORINFO control packets (never relayed, own metrics)
        self.is_neighborinfo = False
        # quantized neighbor table advertised by the sender:
        # tuple of (nid, pdr_class, etx_class, fresh) — only what sender knows
        self.ni_neighbors = None
        # route-discovery probe (simulator equivalent of Meshtastic
        # Traceroute/RouteDiscovery; control traffic, cost-metered)
        self.is_probe = False
        # node the probe is trying to reach (only it responds)
        self.probe_target = None
        # unicast reply travelling back to the probe origin
        self.is_probe_response = False
        # Echo-Probe neighbor discovery at cold start (control traffic)
        self.is_echo_probe = False
        self.is_probe_ack = False
        # priority marker (Emergency bypass)
        self.is_emergency = False
        # LPR potential fields (optional layer, ablated OFF by default)
        self.potential_to_dest = None
        self.cost_estimate = None
        self.packet_class = None
        self.packet_scope = None
        self.potential_version = None
        self.source_potential = None
        # Firmware MeshPacket header field: the hop limit at ORIGIN.
        # Relays copy it unchanged (they only decrement hopLimit), exactly
        # as in meshtastic firmware. Firmware NodeDB computes
        # hops_away = hopStart - hopLimit for the originator of ANY decoded
        # packet (has_hops_away = hopStart set) — pure passive topology
        # evidence at zero marginal airtime: the field is part of the
        # already-modeled header. None = unset (firmware: hopStart 0),
        # and every consumer must degrade gracefully without it.
        self.hopStart = None
        # TX timestamp (for ToA-scaled windows; set at actual TX start)
        self.timestamp_tx = None
        self.hopLimit = self.tx_node.hopLimit


class MeshMessage:
    def __init__(self, origTxNodeId, destId, genTime, seq):
        self.origTxNodeId = origTxNodeId
        self.destId = destId
        self.genTime = genTime
        self.seq = seq
        self.endTime = 0
